'use client';

import { useState, useEffect } from 'react';
import { MainLayout } from '@/components/layout/main-layout';
import { ProtectedRoute } from '@/components/auth/protected-route';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Badge } from '@/components/ui/badge';
import { motion } from 'framer-motion';
import { Loader2, Database, AlertCircle, FileJson, CheckCircle2 } from 'lucide-react';

interface SessionSummary {
  session_id: string;
  status: string;
  segment_count: number;
}

export default function PipelineDataPage() {
  const [sessions, setSessions] = useState<SessionSummary[]>([]);
  const [selectedSession, setSelectedSession] = useState<string>('');
  const [segments, setSegments] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    // Fetch sessions
    const fetchSessions = async () => {
      try {
        const res = await fetch('/api/pulse/api/sessions');
        if (!res.ok) throw new Error('Failed to fetch sessions');
        const data = await res.json();
        if (data.sessions) {
          setSessions(data.sessions);
          if (data.sessions.length > 0) {
            setSelectedSession(data.sessions[data.sessions.length - 1].session_id);
          }
        }
      } catch (err: any) {
        setError(err.message);
      }
    };
    fetchSessions();
  }, []);

  useEffect(() => {
    if (!selectedSession) return;
    
    // Fetch segments for selected session
    const fetchSegments = async () => {
      setLoading(true);
      setError(null);
      try {
        const res = await fetch(`/api/pulse/api/sessions/${selectedSession}/segments`);
        if (!res.ok) throw new Error('Failed to fetch segments');
        const data = await res.json();
        setSegments(data.segments || []);
      } catch (err: any) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };
    
    fetchSegments();
  }, [selectedSession]);

  return (
    <ProtectedRoute>
      <MainLayout 
        title="Pipeline Data" 
        description="Raw telemetry and inference data generated by the ML pipeline"
      >
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-6 flex flex-col h-full"
        >
          {/* Header Controls */}
          <div className="flex flex-col sm:flex-row gap-4 justify-between items-start sm:items-center p-4 rounded-xl border"
               style={{ 
                 background: 'rgba(20, 20, 20, 0.4)', 
                 borderColor: 'rgba(255, 255, 255, 0.1)',
                 backdropFilter: 'blur(10px)' 
               }}>
            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-lg" style={{ background: 'rgba(212, 192, 142, 0.15)' }}>
                <Database className="w-5 h-5 text-[#D4C08E]" />
              </div>
              <div>
                <h2 className="font-semibold text-white">Select Session</h2>
                <p className="text-sm text-gray-400">View segment reports</p>
              </div>
            </div>
            
            <Select value={selectedSession} onValueChange={setSelectedSession}>
              <SelectTrigger className="w-full sm:w-[280px] bg-black/40 border-white/10 flex flex-row items-center border-[1px] border-slate-700 p-2 min-h-12 box-border shadow-none">
                <SelectValue placeholder="Select a session..." />
              </SelectTrigger>
              <SelectContent className="bg-neutral-900 border-neutral-800 text-white">
                {sessions.map((s) => (
                  <SelectItem key={s.session_id} value={s.session_id} className="hover:bg-white/10 hover:text-white cursor-pointer transition-colors focus:bg-white/10 focus:text-white">
                    <div className="flex justify-between items-center w-full gap-2">
                       <span>{s.session_id}</span>
                       <Badge variant="outline" className="text-xs bg-black/40 border-white/10">
                         {s.segment_count} segs
                       </Badge>
                    </div>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Error State */}
          {error && (
            <div className="flex items-center gap-2 p-4 text-red-400 bg-red-400/10 border border-red-400/20 rounded-xl">
              <AlertCircle className="w-5 h-5" />
              <p>{error}</p>
            </div>
          )}

          {/* Loading State */}
          {loading && !error && (
            <div className="flex flex-col items-center justify-center py-20">
              <Loader2 className="w-8 h-8 animate-spin text-[#D4C08E] mb-4" />
              <p className="text-gray-400">Loading pipeline results...</p>
            </div>
          )}

          {/* Data Content */}
          {!loading && !error && segments.length > 0 && (
            <ScrollArea className="flex-1 rounded-xl">
              <div className="space-y-4 pr-4">
                {segments.map((segment, index) => {
                  const hasChallenges = segment.devils_advocate_challenges && segment.devils_advocate_challenges.length > 0;
                  const hasDistresses = segment.distresses && segment.distresses.length > 0;
                  const finalCondition = segment.final_condition || 'Unknown';
                  
                  return (
                    <Card key={segment.segment_id || index} className="overflow-hidden border-white/10 bg-black/40 backdrop-blur-sm">
                      <CardHeader className="pb-3 border-b border-white/5 bg-white/[0.02]">
                        <div className="flex flex-wrap sm:flex-nowrap justify-between gap-4 items-start">
                          <div>
                            <CardTitle className="text-lg flex items-center gap-2 text-white">
                              {segment.segment_id}
                              {hasChallenges ? (
                                <Badge variant="destructive" className="ml-2">Flagged</Badge>
                              ) : (
                                <Badge variant="outline" className="ml-2 bg-green-500/10 text-green-400 border-green-500/20">Optimal</Badge>
                              )}
                            </CardTitle>
                            <CardDescription className="text-gray-400 mt-1">
                              Processed at: {new Date(segment.timestamp * 1000).toLocaleString()}
                            </CardDescription>
                          </div>
                          <div className="flex flex-col items-end gap-1">
                            <span className="text-sm text-gray-400">Condition</span>
                            <span className={`font-medium ${finalCondition === 'Good' ? 'text-green-400' : 'text-yellow-400'}`}>
                              {finalCondition}
                            </span>
                          </div>
                        </div>
                      </CardHeader>
                      <CardContent className="p-0">
                        {/* Highlights Grid */}
                        <div className="grid grid-cols-2 sm:grid-cols-4 gap-px bg-white/5">
                           <div className="p-4 bg-black/40">
                             <div className="text-xs text-gray-400 mb-1">Estimated PCI</div>
                             <div className="text-xl font-semibold text-white">{segment.pci_estimate ?? 'N/A'}</div>
                           </div>
                           <div className="p-4 bg-black/40">
                             <div className="text-xs text-gray-400 mb-1">Computed IRI</div>
                             <div className="text-xl font-semibold text-white">
                               {segment.iri?.iri_value !== null ? segment.iri.iri_value?.toFixed(2) : (segment.iri_value ?? 'N/A')}
                             </div>
                           </div>
                           <div className="p-4 bg-black/40">
                             <div className="text-xs text-gray-400 mb-1">Rut Depth</div>
                             <div className="text-xl font-semibold text-white">{segment.rut_depth_mm !== null ? `${segment.rut_depth_mm} mm` : 'N/A'}</div>
                           </div>
                           <div className="p-4 bg-black/40">
                             <div className="text-xs text-gray-400 mb-1">Distresses Logged</div>
                             <div className="text-xl font-semibold text-red-300">{segment.distresses?.length || 0}</div>
                           </div>
                        </div>

                        {/* Accordion for Deep JSON Inspection */}
                        <Accordion type="single" collapsible className="w-full">
                          <AccordionItem value="raw-json" className="border-none">
                            <AccordionTrigger className="px-5 py-3 hover:bg-white/5 hover:no-underline flex gap-2">
                              <FileJson className="w-4 h-4 text-gray-400" />
                              <span className="text-sm font-medium text-gray-300">View Raw Pipeline Data</span>
                            </AccordionTrigger>
                            <AccordionContent className="p-0 border-t border-white/5">
                              <div className="bg-neutral-950 p-4 overflow-x-auto">
                                <pre className="text-xs text-green-400/90 font-mono leading-relaxed">
                                  {JSON.stringify(segment, null, 2)}
                                </pre>
                              </div>
                            </AccordionContent>
                          </AccordionItem>
                        </Accordion>
                      </CardContent>
                    </Card>
                  );
                })}
              </div>
            </ScrollArea>
          )}

          {!loading && !error && segments.length === 0 && selectedSession && (
            <div className="flex flex-col items-center justify-center py-20 text-center bg-black/20 rounded-xl border border-white/5">
              <CheckCircle2 className="w-12 h-12 text-gray-600 mb-4" />
              <h3 className="text-lg font-medium text-white mb-1">No Segments Found</h3>
              <p className="text-gray-400">This session has no pipeline_result.json records.</p>
            </div>
          )}
        </motion.div>
      </MainLayout>
    </ProtectedRoute>
  );
}
