'use client';

import { MainLayout } from '@/components/layout/main-layout';
import { ProtectedRoute } from '@/components/auth/protected-route';
import { usePulseStore } from '@/lib/store';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { FileText, Download, IndianRupee, Users, Activity } from 'lucide-react';
import { motion } from 'framer-motion';

export default function ApplicationsPage() {
  const { segments } = usePulseStore();

  // Get the most recent segment that has economic or pmgsy data
  const latestData = segments.length > 0 
    ? [...segments].reverse().find(s => s.economic || s.pmgsy_application) 
    : null;

  const eco = latestData?.economic;
  const pmgsy = latestData?.pmgsy_application;

  const handleDownload = async () => {
    if (!latestData?.session_id) return;
    try {
      // Create an invisible iframe/link to trigger download from backend
      const link = document.createElement('a');
      link.href = `/api/pulse/report/${latestData.session_id}`;
      link.setAttribute('download', `PMGSY_Application_${latestData.session_id}.pdf`);
      document.body.appendChild(link);
      link.click();
      link.remove();
    } catch (e) {
      console.error("Failed to download PDF", e);
    }
  };

  return (
    <ProtectedRoute>
      <MainLayout title="PMGSY & Economic Data" description="Official government application drafting and economic impact analysis">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <Card className="border-white/10 bg-black/20">
              <CardContent className="p-6">
                <div className="flex items-center gap-4">
                  <div className="p-3 bg-red-500/20 rounded-xl text-red-400">
                    <IndianRupee className="w-6 h-6" />
                  </div>
                  <div>
                    <p className="text-sm text-gray-400">Estimated Repair Cost</p>
                    <p className="text-2xl font-bold text-white">
                      {pmgsy?.total_budget_lakh ? `₹${pmgsy.total_budget_lakh} Lakh` : 'N/A'}
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="border-white/10 bg-black/20">
              <CardContent className="p-6">
                <div className="flex items-center gap-4">
                  <div className="p-3 bg-yellow-500/20 rounded-xl text-yellow-400">
                    <Activity className="w-6 h-6" />
                  </div>
                  <div>
                    <p className="text-sm text-gray-400">Required Intervention</p>
                    <p className="text-xl font-bold text-white uppercase">
                      {pmgsy?.intervention_type || 'Pending Scan'}
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="border-white/10 bg-black/20">
              <CardContent className="p-6">
                <div className="flex items-center gap-4">
                  <div className="p-3 bg-blue-500/20 rounded-xl text-blue-400">
                    <Users className="w-6 h-6" />
                  </div>
                  <div className="flex-1">
                    <p className="text-sm text-gray-400">Community Impact</p>
                    <p className="text-sm font-medium text-white line-clamp-2">
                      {eco?.narrative || 'Conducting economic cascade analysis...'}
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          <Card className="border-white/10">
            <CardHeader className="bg-black/20 pb-4 flex flex-row items-center justify-between">
              <div>
                <CardTitle className="flex items-center gap-2">
                  <FileText className="w-5 h-5 text-[#D4C08E]" />
                  Auto-Drafted PMGSY Application
                </CardTitle>
                <p className="text-sm text-gray-500 mt-1">Generated by GovernmentPipelineAgent from multi-sensor physics data.</p>
              </div>
              <button 
                onClick={handleDownload} 
                className="flex items-center gap-2 px-4 py-2 bg-[#D4C08E] text-black font-semibold rounded-lg hover:bg-[#b8a577] disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                disabled={!pmgsy?.application_text}
              >
                <Download className="w-4 h-4" />
                Download PDF
              </button>
            </CardHeader>
            <CardContent className="p-6">
              {pmgsy?.application_text ? (
                <div className="prose prose-invert max-w-none">
                  <div className="whitespace-pre-wrap font-serif text-gray-300 leading-relaxed p-6 bg-black/40 rounded-xl border border-white/5">
                    {pmgsy.application_text}
                  </div>
                </div>
              ) : (
                <div className="h-64 flex flex-col items-center justify-center text-gray-500">
                  <p>No application drafted yet. Pipeline must complete a segment analysis.</p>
                </div>
              )}
            </CardContent>
          </Card>
          
        </motion.div>
      </MainLayout>
    </ProtectedRoute>
  );
}
